/**
 * Document Generation Service
 * Creates Word, Excel documents and HTML/PDF from AI responses
 * Uses browser-compatible libraries only
 * 
 * Built by FreedomForged_AI
 */

import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType } from 'docx';
import ExcelJS from 'exceljs';

export type DocumentType = 'word' | 'pdf' | 'excel' | 'powerpoint';

export interface GeneratedDocument {
  blob: Blob;
  filename: string;
  mimeType: string;
}

/**
 * Parse markdown content
 */
function parseContent(content: string) {
  const lines = content.split('\n');
  const paragraphs: string[] = [];
  const tables: string[][] = [];
  let currentTable: string[] = [];
  let inTable = false;
  
  for (const line of lines) {
    if (line.includes('|') && line.trim().startsWith('|')) {
      inTable = true;
      if (!line.includes('---')) {
        currentTable.push(line.split('|').filter(c => c.trim()).map(c => c.trim()).join('\t'));
      }
    } else {
      if (inTable && currentTable.length > 0) {
        tables.push(currentTable);
        currentTable = [];
        inTable = false;
      }
      if (line.trim()) paragraphs.push(line.trim());
    }
  }
  if (currentTable.length > 0) tables.push(currentTable);
  return { paragraphs, tables };
}

/**
 * Generate Word document (.docx)
 */
async function generateWord(title: string, content: string): Promise<GeneratedDocument> {
  const { paragraphs, tables } = parseContent(content);
  const children: (Paragraph | Table)[] = [
    new Paragraph({ text: title, heading: HeadingLevel.TITLE, spacing: { after: 400 } }),
  ];
  
  for (const para of paragraphs) {
    let text = para;
    let heading: typeof HeadingLevel.HEADING_1 | typeof HeadingLevel.HEADING_2 | typeof HeadingLevel.HEADING_3 | undefined;
    
    if (para.startsWith('### ')) { heading = HeadingLevel.HEADING_3; text = para.slice(4); }
    else if (para.startsWith('## ')) { heading = HeadingLevel.HEADING_2; text = para.slice(3); }
    else if (para.startsWith('# ')) { heading = HeadingLevel.HEADING_1; text = para.slice(2); }
    
    if (heading) {
      children.push(new Paragraph({ text: text.replace(/\*\*/g, ''), heading, spacing: { before: 300, after: 150 } }));
    } else if (para.startsWith('• ') || para.startsWith('- ') || para.startsWith('* ')) {
      children.push(new Paragraph({ children: [new TextRun({ text: para.slice(2) })], bullet: { level: 0 }, spacing: { after: 100 } }));
    } else {
      children.push(new Paragraph({ children: [new TextRun({ text: text.replace(/\*\*/g, '') })], spacing: { after: 150 } }));
    }
  }
  
  if (tables.length > 0) {
    const tableData = tables[0].map(row => row.split('\t'));
    if (tableData.length > 0) {
      children.push(new Table({
        rows: tableData.map((row, idx) => new TableRow({
          children: row.map(cell => new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: cell, bold: idx === 0 })] })],
            width: { size: Math.floor(100 / row.length), type: WidthType.PERCENTAGE },
          })),
        })),
        width: { size: 100, type: WidthType.PERCENTAGE },
      }));
    }
  }
  
  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by Outlook AI - FreedomForged_AI | ${new Date().toLocaleDateString()}`, italics: true, size: 20, color: '888888' })],
    spacing: { before: 600 },
  }));
  
  const doc = new Document({ sections: [{ properties: {}, children }] });
  const blob = await Packer.toBlob(doc);
  return { blob, filename: `${title.replace(/[^a-z0-9]/gi, '_')}.docx`, mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' };
}

/**
 * Generate HTML (printable to PDF)
 */
async function generatePDF(title: string, content: string): Promise<GeneratedDocument> {
  const { paragraphs, tables } = parseContent(content);
  let html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>
<style>
  body{font-family:'Segoe UI',Arial,sans-serif;max-width:800px;margin:40px auto;padding:20px;line-height:1.6;background:#fff;color:#333}
  h1{color:#39ff14;border-bottom:2px solid #39ff14;padding-bottom:10px}
  h2{color:#ffb000;margin-top:30px}h3{color:#666}
  table{width:100%;border-collapse:collapse;margin:20px 0}
  th,td{border:1px solid #ddd;padding:12px;text-align:left}
  th{background:#39ff14;color:#000}tr:nth-child(even){background:#f9f9f9}
  ul{margin:10px 0;padding-left:25px}
  .footer{margin-top:40px;padding-top:20px;border-top:1px solid #ddd;color:#888;font-size:12px}
  @media print{body{margin:0;background:#fff}}
</style></head><body><h1>${title}</h1>`;
  
  let inList = false;
  for (const para of paragraphs) {
    const isList = para.startsWith('• ') || para.startsWith('- ') || para.startsWith('* ');
    if (isList && !inList) { html += '<ul>'; inList = true; }
    if (!isList && inList) { html += '</ul>'; inList = false; }
    
    if (para.startsWith('### ')) html += `<h3>${para.slice(4)}</h3>`;
    else if (para.startsWith('## ')) html += `<h2>${para.slice(3)}</h2>`;
    else if (para.startsWith('# ')) html += `<h1>${para.slice(2)}</h1>`;
    else if (isList) html += `<li>${para.slice(2).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</li>`;
    else html += `<p>${para.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</p>`;
  }
  if (inList) html += '</ul>';
  
  if (tables.length > 0) {
    const tableData = tables[0].map(row => row.split('\t'));
    if (tableData.length > 0) {
      html += '<table><thead><tr>';
      tableData[0].forEach(cell => html += `<th>${cell}</th>`);
      html += '</tr></thead><tbody>';
      tableData.slice(1).forEach(row => {
        html += '<tr>'; row.forEach(cell => html += `<td>${cell}</td>`); html += '</tr>';
      });
      html += '</tbody></table>';
    }
  }
  
  html += `<div class="footer">Generated by Outlook AI - FreedomForged_AI | ${new Date().toLocaleDateString()}<br><em>To save as PDF: Press Ctrl+P → Save as PDF</em></div></body></html>`;
  
  return { blob: new Blob([html], { type: 'text/html' }), filename: `${title.replace(/[^a-z0-9]/gi, '_')}.html`, mimeType: 'text/html' };
}

/**
 * Generate Excel (.xlsx)
 */
async function generateExcel(title: string, content: string): Promise<GeneratedDocument> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Outlook AI - FreedomForged_AI';
  const worksheet = workbook.addWorksheet(title.substring(0, 31));
  
  const { tables, paragraphs } = parseContent(content);
  const tableData = tables.length > 0 ? tables[0].map(row => row.split('\t')) : null;
  
  if (tableData && tableData.length > 0) {
    tableData.forEach((row, idx) => {
      const excelRow = worksheet.addRow(row);
      if (idx === 0) {
        excelRow.eachCell(cell => {
          cell.font = { bold: true, color: { argb: 'FF000000' } };
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF39FF14' } };
          cell.alignment = { horizontal: 'center' };
        });
      }
    });
    worksheet.columns.forEach(col => col.width = 20);
  } else {
    paragraphs.forEach(line => worksheet.addRow([line]));
    worksheet.getColumn(1).width = 100;
  }
  
  worksheet.addRow([]);
  worksheet.addRow([`Generated by Outlook AI - FreedomForged_AI | ${new Date().toLocaleDateString()}`]).font = { italic: true, color: { argb: 'FF888888' } };
  
  const buffer = await workbook.xlsx.writeBuffer();
  return { blob: new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), filename: `${title.replace(/[^a-z0-9]/gi, '_')}.xlsx`, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' };
}

/**
 * Generate PowerPoint-like HTML presentation
 */
async function generatePowerPoint(title: string, content: string): Promise<GeneratedDocument> {
  const { paragraphs, tables } = parseContent(content);
  const slides: { title: string; bullets: string[] }[] = [];
  let currentSlide = { title: title, bullets: [] as string[] };
  
  for (const para of paragraphs) {
    if (para.startsWith('## ') || para.startsWith('# ')) {
      if (currentSlide.bullets.length > 0 || currentSlide.title !== title) slides.push(currentSlide);
      currentSlide = { title: para.replace(/^#+ /, ''), bullets: [] };
    } else if (!para.startsWith('### ')) {
      currentSlide.bullets.push(para.replace(/\*\*/g, ''));
      if (currentSlide.bullets.length >= 6) {
        slides.push(currentSlide);
        currentSlide = { title: currentSlide.title + ' (cont.)', bullets: [] };
      }
    }
  }
  if (currentSlide.bullets.length > 0) slides.push(currentSlide);
  
  let html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Segoe UI',Arial;background:#1a1a1a;color:#e0e0e0}
  .slide{width:100%;min-height:100vh;padding:60px;display:flex;flex-direction:column;justify-content:center;page-break-after:always;border-bottom:2px solid #39ff14}
  .slide h1{color:#39ff14;font-size:48px;margin-bottom:40px;text-shadow:0 0 20px rgba(57,255,20,0.5)}
  .slide h2{color:#ffb000;font-size:36px;margin-bottom:30px}
  .slide ul{font-size:24px;line-height:2;padding-left:40px}
  .slide li{margin:10px 0}
  .title-slide{text-align:center;justify-content:center}
  .title-slide h1{font-size:64px;margin-bottom:20px}
  .title-slide p{color:#ffb000;font-size:24px}
  .end-slide{text-align:center}
  .end-slide h1{color:#39ff14}
  .footer{color:#666;font-size:14px;margin-top:auto;padding-top:40px}
  @media print{.slide{page-break-after:always;height:100vh}}
</style></head><body>
<div class="slide title-slide">
  <h1>${title}</h1>
  <p>Generated by Outlook AI</p>
  <p style="color:#888;margin-top:20px">FreedomForged_AI | ${new Date().toLocaleDateString()}</p>
</div>`;
  
  slides.forEach(slide => {
    html += `<div class="slide"><h2>${slide.title}</h2><ul>`;
    slide.bullets.forEach(b => html += `<li>${b}</li>`);
    html += `</ul><div class="footer">Outlook AI - FreedomForged_AI</div></div>`;
  });
  
  if (tables.length > 0) {
    const tableData = tables[0].map(row => row.split('\t'));
    html += `<div class="slide"><h2>Data</h2><table style="width:100%;border-collapse:collapse;margin-top:30px">`;
    html += `<thead><tr>${tableData[0].map(c => `<th style="background:#39ff14;color:#000;padding:15px;text-align:left">${c}</th>`).join('')}</tr></thead><tbody>`;
    tableData.slice(1).forEach(row => html += `<tr>${row.map(c => `<td style="padding:15px;border-bottom:1px solid #333">${c}</td>`).join('')}</tr>`);
    html += '</tbody></table></div>';
  }
  
  html += `<div class="slide end-slide"><h1>Thank You</h1><p style="color:#ffb000;font-size:24px;margin-top:20px">Powered by Outlook AI - FreedomForged_AI</p></div></body></html>`;
  
  return { blob: new Blob([html], { type: 'text/html' }), filename: `${title.replace(/[^a-z0-9]/gi, '_')}_presentation.html`, mimeType: 'text/html' };
}

/**
 * Download document
 */
export function downloadDocument(doc: GeneratedDocument): void {
  const url = URL.createObjectURL(doc.blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = doc.filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Document service
 */
export const documentService = {
  async createWord(title: string, content: string) {
    const doc = await generateWord(title, content);
    downloadDocument(doc);
    return doc;
  },
  async createPDF(title: string, content: string) {
    const doc = await generatePDF(title, content);
    downloadDocument(doc);
    return doc;
  },
  async createExcel(title: string, content: string) {
    const doc = await generateExcel(title, content);
    downloadDocument(doc);
    return doc;
  },
  async createPowerPoint(title: string, content: string) {
    const doc = await generatePowerPoint(title, content);
    downloadDocument(doc);
    return doc;
  },
};

export default documentService;
